In [1]:
from pandas_datareader import data as pdr
from datetime import date
import yfinance as yf
yf.pdr_override() 
import pandas as pd

In [2]:
tickers = [
    'FICO', 'BG', 'PODD', 'STLD', 'FSLR', 'ACGL', 'TRGP', 'EQT', 'PCG',
    'CSGP', 'INVH', 'KDP', 'ON', 'VICI', 'WBD', 'CPT', 'MOH', 'NDSN', 'CEG',
    'FDS', 'SEDG', 'EPAM', 'BRO', 'CDAY', 'MTCH', 'TECH', 'MRNA', 'OGN', 'CRL',
    'PTC', 'CZR', 'GNRC', 'NXPI', 'MPWR', 'TRMB', 'ENPH', 'TSLA', 'POOL', 'CTLT',
    'ETSY', 'TER', 'BIO', 'TDY', 'TYL', 'WST', 'DXCM', 'DPZ', 'CARR', 'OTIS',
    'IR', 'PAYC', 'LYV', 'STE', 'ZBRA', 'ODFL', 'WRB', 'NOW', 'LVS', 'NVR', 'CDW',
    'IEX', 'LDOS', 'TMUS', 'MKTX', 'AMCR', 'CTVA', 'DD', 'DOW', 'WAB', 'ATO', 'TFX',
    'FRC', 'CE', 'FANG', 'LW', 'JKHY', 'KEYS', 'FTNT', 'ROL', 'ANET', 'CPRT', 'FLT',
    'BR', 'EVRG', 'MSCI', 'TTWO', 'HII', 'NCLH', 'CDNS', 'SBAC', 'IQV', 'AOS', 'MGM',
    'PKG', 'RMD', 'BKR', 'ALGN', 'ANSS', 'RE', 'HLT', 'IT', 'DXC', 'ARE', 'AMD', 'RJF',
    'SNPS', 'DISH', 'REG', 'CBOE', 'INCY', 'IDXX', 'MAA', 'COO', 'CHTR', 'MTD', 'ALB',
    'LNT', 'FTV', 'TDG', 'AJG', 'LKQ', 'DLR', 'ALK', 'GPN', 'ULTA', 'CNC', 'HOLX',
    'UDR', 'AWK', 'FRT', 'CFG', 'EXR', 'WTW', 'CHD', 'ILMN', 'SYF', 'HPE', 'VRSK',
    'FOX', 'NWS', 'UAL', 'ATVI', 'PYPL', 'AAP', 'KHC', 'JBHT', 'QRVO', 'O', 'AAL',
    'EQIX', 'HSIC', 'SWKS', 'HCA', 'RCL', 'URI', 'UHS', 'MLM', 'AVGO', 'GOOGL', 'ESS',
    'TSCO', 'META', 'MHK', 'ALLE', 'AME', 'VRTX', 'DAL', 'NWSA', 'FOXA', 'ZTS', 'GM',
    'REGN', 'ABBV', 'APTV', 'GRMN', 'DG', 'MDLZ', 'PNR', 'LYB', 'STX', 'LRCX', 'MNST',
    'KMI', 'PSX', 'CCI', 'BWA', 'DLTR', 'XYL', 'TEL', 'MOS', 'ACN', 'MPC', 'CMG', 'BLK',
    'EW', 'FFIV', 'NFLX', 'TT', 'JCI', 'CB', 'KMX', 'OKE', 'BRK.B', 'NRG', 'ROP', 'ROST',
    'V', 'BKNG', 'FMC', 'PWR', 'WDC', 'ORLY', 'HRL', 'VTR', 'WELL', 'IRM', 'ES', 'RSG',
    'XRAY', 'WYNN', 'SJM', 'WEC', 'NDAQ', 'APH', 'PXD', 'LHX', 'FAST', 'CRM', 'CF', 'IVZ',
    'DVA', 'MA', 'CTRA', 'ISRG', 'PEAK', 'PM', 'AMT', 'J', 'EXPD', 'EXPE', 'ICE', 'MCHP',
    'AKAM', 'DFS', 'AIZ', 'HST', 'CHRW', 'RL', 'AVB', 'CTSH', 'CBRE', 'FIS', 'CME', 'JNPR',
    'KIM', 'GOOG', 'BXP', 'VRSN', 'EL', 'AMZN', 'LEN', 'AMP', 'PSA', 'TSN', 'STZ', 'DHI',
    'LH', 'TPR', 'TMO', 'GILD', 'VTRS', 'MTB', 'BIIB', 'PLD', 'GEN', 'MKC', 'STT', 'VLO',
    'DGX', 'CMCSA', 'TRV', 'ELV', 'EBAY', 'EA', 'GS', 'PFG', 'PRU', 'UPS', 'SPG', 'WAT',
    'SRE', 'EQR', 'NVDA', 'PPL', 'ABC', 'ZBH', 'ZION', 'FISV', 'CTAS', 'SYK', 'MET', 'INTU',
    'RHI', 'EOG', 'NI', 'DVN', 'SBUX', 'A', 'ADI', 'PNW', 'QCOM', 'VMC', 'BBY', 'NTAP',
    'AFL', 'MCK', 'CCL', 'DHR', 'AES', 'PAYX', 'RF', 'COF', 'MCO', 'MAR', 'BEN', 'NTRS',
    'OMC', 'CINF', 'TFC', 'FE', 'YUM', 'KLAC', 'HBAN', 'PGR', 'APA', 'EFX', 'SCHW', 'CAH',
    'ADBE', 'AZO', 'AON', 'FITB', 'CMA', 'ALL', 'DRI', 'L', 'BK', 'AMAT', 'GLW', 'BSX',
    'PARA', 'MU', 'LUV', 'UNH', 'MSFT', 'KEY', 'EMN', 'CSCO', 'COST', 'MS', 'IPG', 'LIN',
    'AMGN', 'AEE', 'ADSK', 'K', 'ORCL', 'GL', 'NWL', 'ECL', 'NKE', 'C', 'PNC', 'HD', 'AVY',
    'MMC', 'SYY', 'MDT', 'ITW', 'PH', 'DOV', 'TJX', 'CNP', 'PKI', 'APD', 'NUE', 'BALL',
    'HAS', 'HES', 'PHM', 'LOW', 'T', 'VZ', 'BBWI', 'CAG', 'AAPL', 'BF.B', 'SNA', 'SWK',
    'WMT', 'MAS', 'GWW', 'ADP', 'FDX', 'PCAR', 'AIG', 'WBA', 'VFC', 'TXT', 'INTC', 'TGT',
    'AXP', 'BAC', 'CI', 'DIS', 'DUK', 'LNC', 'TAP', 'NEE', 'WFC', 'IFF', 'JPM', 'WMB',
    'HPQ', 'GPC', 'JNJ', 'BAX', 'BDX', 'LLY', 'MCD', 'NEM', 'CLX', 'CMI', 'EMR', 'SHW',
    'MMM', 'ABT', 'ADM', 'MO', 'AEP', 'BA', 'BMY', 'CPB', 'CAT', 'CVX', 'CMS', 'KO', 'CL',
    'COP', 'ED', 'CSX', 'CVS', 'DE', 'DTE', 'ETN', 'EIX', 'ETR', 'EXC', 'XOM', 'F', 'GD',
    'GE', 'GIS', 'HAL', 'HIG', 'HSY', 'HON', 'HWM', 'IBM', 'IP', 'KMB', 'KR', 'LMT', 'MRO',
    'MRK', 'MSI', 'NSC', 'NOC', 'OXY', 'PEP', 'PFE', 'PPG', 'PG', 'PEG', 'RTX', 'SPGI',
    'SLB', 'SEE', 'SO', 'UNP', 'WRK', 'XEL', 'D', 'FCX', 'HUM', 'ROK', 'TROW', 'TXN',
    'USB', 'WM', 'WY', 'WHR'
]

In [3]:
prices = pdr.get_data_yahoo(tickers, start='2020-01-01', end=date.today())['Adj Close']

[*********************100%***********************]  502 of 502 completed

2 Failed downloads:
- BF.B: No data found for this date range, symbol may be delisted
- BRK.B: No timezone found, symbol may be delisted

In [4]:
prices

,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACGL,ACN,ADBE,...,WYNN,XEL,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,84.108360,28.982893,148.484299,73.449379,76.495041,81.061348,82.122169,43.400002,199.948410,334.429993,...,142.405029,57.058811,59.038685,54.990799,76.823204,96.286110,141.331955,259.140015,47.579472,131.088669
2020-01-03,82.757935,27.548195,148.493622,72.735298,75.768951,80.041878,81.121025,43.349998,199.615433,331.809998,...,140.292755,57.333218,58.564053,54.382259,77.275383,95.984512,140.962509,256.049988,46.908070,131.108215
2020-01-06,83.002571,27.219410,146.053177,73.314880,76.366920,81.213783,81.546028,43.520000,198.311951,333.709991,...,140.015091,57.250893,59.013699,54.681702,76.775116,95.927971,140.147842,258.010010,46.336460,130.101624
2020-01-07,83.257004,27.119778,144.320648,72.970093,75.931244,80.632607,81.092690,43.160000,194.030411,333.390015,...,140.679504,57.131985,58.530731,54.971481,76.486465,96.097603,140.024734,256.470001,46.055191,130.541428
2020-01-08,84.078987,27.737495,142.662659,74.143906,76.469406,81.413864,81.423264,42.730000,194.410995,337.869995,...,141.562103,57.077106,57.648075,55.551048,76.746246,96.267250,141.701385,247.639999,46.508839,130.257996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-18,139.000000,13.290000,126.650002,166.470001,159.589996,167.410004,104.150002,72.250000,279.959991,377.549988,...,112.150002,69.760002,116.940002,40.560001,104.190002,137.580002,134.320007,300.630005,30.459999,174.076141
2023-04-19,138.929993,13.630000,128.110001,167.630005,161.210007,164.479996,112.290001,72.129997,279.899994,380.109985,...,112.120003,70.589996,116.570000,40.590000,103.739998,137.119995,138.119995,292.760010,32.720001,174.604996
2023-04-20,135.529999,13.320000,128.369995,166.649994,161.740005,165.960007,110.349998,72.190002,275.549988,380.260010,...,113.690002,70.690002,115.639999,40.849998,104.010002,137.500000,138.350006,290.519989,31.120001,174.399994
2023-04-21,138.500000,13.400000,128.210007,165.020004,162.410004,166.729996,111.660004,71.680000,276.329987,377.670013,...,114.110001,70.440002,116.010002,41.090000,104.309998,138.330002,137.919998,287.899994,29.350000,176.880005
2023-04-24,138.479996,13.320000,126.830002,165.330002,164.080002,167.710007,110.400002,72.510002,277.250000,377.339996,...,114.480003,71.029999,118.199997,41.439999,104.540001,138.899994,138.139999,288.190002,28.270000,176.350006

In [5]:
prices = prices.dropna(axis = 1)

In [6]:
prices.describe()

,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACGL,ACN,ADBE,...,WYNN,XEL,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
count,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,...,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000,833.000000
mean,124.062286,16.798558,165.125955,131.097456,113.586452,121.776030,106.298153,42.635114,267.880520,448.561633,...,91.672580,64.702354,65.201383,46.672538,95.623115,109.442029,129.332140,369.109099,47.161504,165.889161
std,26.132080,4.291021,33.939803,30.169842,29.043314,26.418243,13.526920,10.933487,53.130986,100.915590,...,22.974872,4.722230,26.571172,10.646121,18.770508,16.594147,17.342931,120.343650,12.169152,26.313422
min,62.012177,9.040000,70.084999,54.999004,55.841316,70.748238,59.583961,22.240000,137.243240,275.200012,...,43.020000,46.031078,26.564507,26.622564,54.661537,53.503773,76.377983,161.509995,22.009783,90.683159
25%,104.349762,13.460000,141.498901,117.103310,87.111229,98.004326,98.916718,34.889999,230.226685,368.299988,...,73.570000,61.481010,40.778973,37.410629,81.428871,98.783485,116.494339,268.269989,36.336536,150.038376
50%,128.441666,16.260000,162.431046,137.940216,107.176361,117.689980,107.074837,42.040001,273.393829,443.290009,...,86.790001,64.778862,57.298557,46.268211,96.146454,113.511093,126.843605,326.970001,50.378960,161.722672
75%,144.688156,19.629999,193.215256,151.782837,142.390106,145.125031,115.712440,46.759998,304.356201,500.809998,...,108.459999,67.668526,87.300041,55.618607,110.419327,122.185013,142.019363,488.309998,55.113422,183.165985
max,177.363724,30.469999,230.368713,180.683868,167.007950,173.455414,137.809647,72.510002,406.562866,688.369995,...,150.943390,75.774223,118.260002,67.512863,135.543701,138.899994,170.799347,614.549988,71.756210,244.131577

In [7]:
prices.to_csv('SP500Data.csv')